# Generated by Django 3.2.11 on 2022-02-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QrInfo',
            fields=[
                ('qr_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='qr_id')),
                ('qr_category', models.CharField(choices=[('IN', 'check in'), ('OUT', 'check out')], default='IN', max_length=3, verbose_name='qr 카테고리')),
                ('start_date', models.DateTimeField(verbose_name='qr 시작날짜')),
                ('start_time', models.DateTimeField(verbose_name='qr 시작시각')),
                ('end_date', models.DateTimeField(verbose_name='qr 끝날짜')),
                ('end_time', models.DateTimeField(verbose_name='qr 끝시간')),
                ('qr_content', models.CharField(max_length=50, verbose_name='qr 내용')),
                ('qr_notice', models.CharField(max_length=50, verbose_name='qr 공지')),
            ],
            options={
                'verbose_name': 'QR table',
                'db_table': 'qr',
                'ordering': ['start_date'],
                'managed': True,
            },
        ),
    ]
